-- Add concept_tag column for three-pass AI generation pipeline
ALTER TABLE cards ADD COLUMN IF NOT EXISTS concept_tag TEXT;

-- Expand card_type constraint to include new types generated by the three-pass pipeline
-- Preserves all legacy values so existing cards are unaffected
ALTER TABLE cards DROP CONSTRAINT IF EXISTS cards_card_type_check;
ALTER TABLE cards ADD CONSTRAINT cards_card_type_check
  CHECK (card_type IN (
    'concept', 'definition', 'relationship', 'application', 'example',
    'conceptual', 'comparison', 'edge_case'
  ));
